name: Run-PDFReports-Notebook

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: sudo apt install npm
      - run: sudo chown -R $USER /usr/local/lib/node_modules
      - run: sudo chown -R $USER /usr/local/bin/
      - run: npm install -g electron@6.1.4 orca
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: pip install papermill
      - run: papermill report-pdf.ipynb report-pdf-output.ipynb